"""六爻占卜引擎 - Liuyao (I Ching) divination via coin toss simulation.

Core concepts:
  - 6 lines (爻) generated from bottom (初) to top (上)
  - 3 coins per line: sum 6=老阴(changing), 7=少阳, 8=少阴, 9=老阳(changing)
  - 本卦 (original hexagram) built from all 6 lines
  - 变卦 (changed hexagram) = 本卦 with changing lines flipped
  - 宫 (palace, 八宫): 乾坎艮震巽离坤兑, each with a 五行
  - 世应: host/guest line positions
  - 六亲: 6 relationships based on wuxing interactions
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import random

# ============================================================
# Basic constants
# ============================================================

DIZHI = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]

# 地支五行
DIZHI_WUXING: Dict[str, str] = {
    "子": "水", "丑": "土", "寅": "木", "卯": "木",
    "辰": "土", "巳": "火", "午": "火", "未": "土",
    "申": "金", "酉": "金", "戌": "土", "亥": "水",
}

# 三爻卦编码 (从下到上: 阳=1, 阴=0)
# 乾=111, 兑=110, 离=101, 震=100, 巽=011, 坎=010, 艮=001, 坤=000
TRIGRAM_NAMES: Dict[int, str] = {
    0b111: "乾", 0b110: "兑", 0b101: "离", 0b100: "震",
    0b011: "巽", 0b010: "坎", 0b001: "艮", 0b000: "坤",
}

TRIGRAM_BY_NAME: Dict[str, int] = {v: k for k, v in TRIGRAM_NAMES.items()}

# 八卦宫位五行
PALACE_WUXING: Dict[int, str] = {
    0: "土",  # 坤
    1: "土",  # 艮
    2: "水",  # 坎
    3: "木",  # 巽
    4: "木",  # 震
    5: "火",  # 离
    6: "金",  # 兑
    7: "金",  # 乾
}

# 纳甲: (内卦下层初爻起始地支索引, 外卦上层四爻起始地支索引, 是否阳卦)
# 阳卦内卦从起点顺行(+2每次), 阴卦内卦从起点逆行(-2每次)
TRIGRAM_NAJIA: Dict[str, Tuple[int, int, bool]] = {
    "乾": (0, 6, True),   # 子(0), 午(6)
    "兑": (5, 11, False),  # 巳(5), 亥(11)
    "离": (3, 9, False),   # 卯(3), 酉(9)
    "震": (0, 6, True),   # 子(0), 午(6)
    "巽": (1, 7, False),   # 丑(1), 未(7)
    "坎": (2, 8, True),   # 寅(2), 申(8)
    "艮": (4, 10, True),   # 辰(4), 戌(10)
    "坤": (7, 1, False),   # 未(7), 丑(1)
}

# 八宫卦序 -- 64 卦查询表
# key: hexagram_value = (upper_trigram << 3) | lower_trigram (6-bit, bottom line=LSB)
# value: (name, palace_index, shi_position)
# palace_index matches TRIGRAM_NAMES keys
HEXAGRAM_TABLE: Dict[int, Tuple[str, int, int]] = {
    # 乾宫八卦 (属金)
    0b111111: ("乾为天", 7, 5),
    0b111011: ("天风姤", 7, 0),
    0b111001: ("天山遁", 7, 1),
    0b111000: ("天地否", 7, 2),
    0b011000: ("风地观", 7, 3),
    0b001000: ("山地剥", 7, 4),
    0b101000: ("火地晋", 7, 3),   # 游魂
    0b101111: ("火天大有", 7, 2),  # 归魂

    # 坎宫八卦 (属水)
    0b010010: ("坎为水", 2, 5),
    0b010110: ("水泽节", 2, 0),
    0b010100: ("水雷屯", 2, 1),
    0b010101: ("水火既济", 2, 2),
    0b110101: ("泽火革", 2, 3),
    0b100101: ("雷火丰", 2, 4),
    0b000101: ("地火明夷", 2, 3),  # 游魂
    0b000010: ("地水师", 2, 2),    # 归魂

    # 艮宫八卦 (属土)
    0b001001: ("艮为山", 1, 5),
    0b001101: ("山火贲", 1, 0),
    0b001111: ("山天大畜", 1, 1),
    0b001110: ("山泽损", 1, 2),
    0b101110: ("火泽睽", 1, 3),
    0b111110: ("天泽履", 1, 4),
    0b011110: ("风泽中孚", 1, 3),  # 游魂
    0b011001: ("风山渐", 1, 2),    # 归魂

    # 震宫八卦 (属木)
    0b100100: ("震为雷", 4, 5),
    0b100000: ("雷地豫", 4, 0),
    0b100010: ("雷水解", 4, 1),
    0b100011: ("雷风恒", 4, 2),
    0b000011: ("地风升", 4, 3),
    0b010011: ("水风井", 4, 4),
    0b110011: ("泽风大过", 4, 3),  # 游魂
    0b110100: ("泽雷随", 4, 2),    # 归魂

    # 巽宫八卦 (属木)
    0b011011: ("巽为风", 3, 5),
    0b011111: ("风天小畜", 3, 0),
    0b011101: ("风火家人", 3, 1),
    0b011100: ("风雷益", 3, 2),
    0b111100: ("天雷无妄", 3, 3),
    0b101100: ("火雷噬嗑", 3, 4),
    0b001100: ("山雷颐", 3, 3),    # 游魂
    0b001011: ("山风蛊", 3, 2),    # 归魂

    # 离宫八卦 (属火)
    0b101101: ("离为火", 5, 5),
    0b101001: ("火山旅", 5, 0),
    0b101011: ("火风鼎", 5, 1),
    0b101010: ("火水未济", 5, 2),
    0b001010: ("山水蒙", 5, 3),
    0b011010: ("风水涣", 5, 4),
    0b111010: ("天水讼", 5, 3),    # 游魂
    0b111101: ("天火同人", 5, 2),   # 归魂

    # 坤宫八卦 (属土)
    0b000000: ("坤为地", 0, 5),
    0b000100: ("地雷复", 0, 0),
    0b000110: ("地泽临", 0, 1),
    0b000111: ("地天泰", 0, 2),
    0b100111: ("雷天大壮", 0, 3),
    0b110111: ("泽天夬", 0, 4),
    0b010111: ("水天需", 0, 3),    # 游魂
    0b010000: ("水地比", 0, 2),    # 归魂

    # 兑宫八卦 (属金)
    0b110110: ("兑为泽", 6, 5),
    0b110010: ("泽水困", 6, 0),
    0b110000: ("泽地萃", 6, 1),
    0b110001: ("泽山咸", 6, 2),
    0b010001: ("水山蹇", 6, 3),
    0b000001: ("地山谦", 6, 4),
    0b100001: ("雷山小过", 6, 3),  # 游魂
    0b100110: ("雷泽归妹", 6, 2),  # 归魂
}

# Reverse lookup: name -> hexagram value
HEXAGRAM_BY_NAME: Dict[str, int] = {v[0]: k for k, v in HEXAGRAM_TABLE.items()}

# All 64 hexagram values for verification
ALL_HEXAGRAM_VALUES = set(HEXAGRAM_TABLE.keys())


# ============================================================
# 五行 utilities
# ============================================================

def wuxing_generates(wx: str) -> str:
    """Return the element generated by wx. 木→火→土→金→水→木"""
    cycle = {"木": "火", "火": "土", "土": "金", "金": "水", "水": "木"}
    return cycle[wx]


def wuxing_controls(wx: str) -> str:
    """Return the element controlled by wx. 木→土→水→火→金→木"""
    cycle = {"木": "土", "土": "水", "水": "火", "火": "金", "金": "木"}
    return cycle[wx]


def calc_liuqin(palace_wuxing: str, line_wuxing: str) -> str:
    """Calculate the 六亲 relationship between a palace and a line.

    Relationships:
      - 同我 (same element)       -> 兄弟
      - 我生 (palace generates)   -> 子孙
      - 生我 (line generates)     -> 父母
      - 我克 (palace controls)    -> 妻财
      - 克我 (line controls)      -> 官鬼
    """
    if palace_wuxing == line_wuxing:
        return "兄弟"
    if wuxing_generates(palace_wuxing) == line_wuxing:
        return "子孙"
    if wuxing_generates(line_wuxing) == palace_wuxing:
        return "父母"
    if wuxing_controls(palace_wuxing) == line_wuxing:
        return "妻财"
    if wuxing_controls(line_wuxing) == palace_wuxing:
        return "官鬼"
    return "兄弟"


# ============================================================
# Data model
# ============================================================

@dataclass
class LiuyaoResult:
    """六爻占卜结果

    Attributes:
        original_hexagram: 本卦卦名, e.g. "天地否"
        changed_hexagram: 变卦卦名, e.g. "风地观" (empty string if no changing lines)
        lines: 6爻详情, each a dict with keys:
            - type: "老阴"|"少阳"|"少阴"|"老阳"
            - yao_type: "世"|"应"|""
            - liuqin: "兄弟"|"子孙"|"父母"|"妻财"|"官鬼"
            - dizhi: 地支
        shi_yao: 世爻位置 (0-5)
        ying_yao: 应爻位置 (0-5)
        changing_lines: 动爻索引, e.g. [2, 4] (empty if 静卦)
        palace: 所属宫名, e.g. "乾"
        palace_wuxing: 宫五行, e.g. "金"
        original_hexagram_value: 本卦6-bit数值 (binary: 上卦|下卦)
        changed_hexagram_value: 变卦6-bit数值
        question: 所问之事
    """
    original_hexagram: str
    changed_hexagram: str
    lines: List[Dict[str, str]]
    shi_yao: int
    ying_yao: int
    changing_lines: List[int]
    palace: str
    palace_wuxing: str
    original_hexagram_value: int
    changed_hexagram_value: int
    question: str = ""
    raw_data: dict = field(default_factory=dict)


# ============================================================
# Liuyao Engine
# ============================================================

class LiuyaoEngine:
    """六爻占卜引擎

    Usage:
        engine = LiuyaoEngine()
        result = engine.cast(method="random", question="财运", seed=42)
    """

    def cast(self, method: str = "random", question: str = "",
             seed: Optional[int] = None) -> LiuyaoResult:
        """起卦占卜

        Args:
            method: 起卦方法. "random" 模拟三枚硬币抛六次.
            question: 所问之事 (optional).
            seed: 随机种子, 用于可重复测试.

        Returns:
            LiuyaoResult containing the complete divination result.
        """
        if method == "random":
            return self._cast_coins(question, seed)
        raise ValueError(f"Unsupported method: {method}. Supported: 'random'.")

    def lookup_hexagram(self, upper: str, lower: str) -> Optional[Tuple[str, int, int]]:
        """Look up a hexagram by its upper and lower trigram names.

        Args:
            upper: Upper trigram name (乾兑离震巽坎艮坤).
            lower: Lower trigram name.

        Returns:
            (name, palace_index, shi_position) or None if not found.
        """
        u_val = TRIGRAM_BY_NAME.get(upper)
        l_val = TRIGRAM_BY_NAME.get(lower)
        if u_val is None or l_val is None:
            return None
        value = (u_val << 3) | l_val
        return HEXAGRAM_TABLE.get(value)

    def get_line_dizhi(self, upper: str, lower: str) -> List[str]:
        """Calculate the 纳甲 (Najia) earthly branch for each of the 6 lines.

        Returns:
            List of 6 地支, from line 0 (初爻) to line 5 (上爻).
        """
        u_lower_start, u_upper_start, u_is_yang = TRIGRAM_NAJIA[upper]
        l_lower_start, _, l_is_yang = TRIGRAM_NAJIA[lower]

        dizhi: List[str] = []
        for i in range(6):
            if i < 3:
                # Lower trigram lines (初, 二, 三)
                if l_is_yang:
                    dz_idx = (l_lower_start + i * 2) % 12
                else:
                    dz_idx = (l_lower_start - i * 2) % 12
            else:
                # Upper trigram lines (四, 五, 上)
                if u_is_yang:
                    dz_idx = (u_upper_start + (i - 3) * 2) % 12
                else:
                    dz_idx = (u_upper_start - (i - 3) * 2) % 12
            dizhi.append(DIZHI[dz_idx])
        return dizhi

    def _cast_coins(self, question: str = "",
                    seed: Optional[int] = None) -> LiuyaoResult:
        """Simulate tossing 3 coins 6 times to generate a hexagram.

        Each coin: heads (阳) = 2, tails (阴) = 3.
        Sum values:
            6 = 老阴 (changing yin)
            7 = 少阳 (young yang)
            8 = 少阴 (young yin)
            9 = 老阳 (changing yang)
        """
        rng = random.Random(seed)

        raw_lines: List[Dict] = []
        hex_value = 0  # Build 6-bit hexagram from bottom (LSB)

        for i in range(6):
            total = rng.choice([2, 3]) + rng.choice([2, 3]) + rng.choice([2, 3])

            if total == 6:
                line_type = "老阴"
                yin_yang = 0
            elif total == 7:
                line_type = "少阳"
                yin_yang = 1
            elif total == 8:
                line_type = "少阴"
                yin_yang = 0
            elif total == 9:
                line_type = "老阳"
                yin_yang = 1
            else:
                raise RuntimeError(f"Unexpected coin sum: {total}")

            if yin_yang:
                hex_value |= (1 << i)

            raw_lines.append({
                "index": i,
                "type": line_type,
                "yin_yang": yin_yang,
                "changing": line_type in ("老阴", "老阳"),
                "value": total,
            })

        # Lookup hexagram
        entry = HEXAGRAM_TABLE[hex_value]
        hex_name, palace_idx, shi_pos = entry

        ying_pos = (shi_pos + 3) % 6

        # Line 地支
        upper_val = (hex_value >> 3) & 0b111
        lower_val = hex_value & 0b111
        upper_name = TRIGRAM_NAMES[upper_val]
        lower_name = TRIGRAM_NAMES[lower_val]
        line_dizhi = self.get_line_dizhi(upper_name, lower_name)

        # Build detailed lines with 六亲 and 世应
        palace_wx = PALACE_WUXING[palace_idx]

        full_lines: List[Dict] = []
        changing_lines: List[int] = []

        for i, rl in enumerate(raw_lines):
            dz = line_dizhi[i]
            dz_wx = DIZHI_WUXING[dz]
            liuqin = calc_liuqin(palace_wx, dz_wx)

            if i == shi_pos:
                yao_type = "世"
            elif i == ying_pos:
                yao_type = "应"
            else:
                yao_type = ""

            full_lines.append({
                "type": rl["type"],
                "yao_type": yao_type,
                "liuqin": liuqin,
                "dizhi": dz,
            })

            if rl["changing"]:
                changing_lines.append(i)

        # Calculate 变卦 (flip changing lines)
        changed_value = hex_value
        for i in changing_lines:
            changed_value ^= (1 << i)

        changed_name = ""
        if changing_lines:
            changed_entry = HEXAGRAM_TABLE.get(changed_value)
            if changed_entry:
                changed_name = changed_entry[0]
        else:
            changed_name = hex_name  # 静卦: same as original

        return LiuyaoResult(
            original_hexagram=hex_name,
            changed_hexagram=changed_name,
            lines=full_lines,
            shi_yao=shi_pos,
            ying_yao=ying_pos,
            changing_lines=changing_lines,
            palace=TRIGRAM_NAMES[palace_idx],
            palace_wuxing=palace_wx,
            original_hexagram_value=hex_value,
            changed_hexagram_value=changed_value,
            question=question,
            raw_data={
                "raw_lines": raw_lines,
                "line_dizhi": line_dizhi,
                "upper_trigram": upper_name,
                "lower_trigram": lower_name,
            },
        )
